// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vniujpmsoihgfwcpzmcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaXVqcG1zb2loZ2Z3Y3B6bWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTY5OTYsImV4cCI6MjA3MzM3Mjk5Nn0.wacTNHqCd70x6rjl8-B7LcXpFP2UXu6SR1uEEnhOfB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});